language: node_js
node_js: stable

# S: Build Lifecycle
install:
#  - npm install -g hexo
#  - npm install -g hexo-deploy-git
  - npm install


before_script:
 # - npm install -g gulp
#   - npm install -g hexo
   - hexo -v

script:
  - hexo clean
  - hexo g

after_success:
  - cd ./public
  - git init
  - git config user.name "FuJunZhi"
  - git config user.email "fujunzhi1007@163.com"
  - git add .
  - git commit -m "Update blog!"
  - git push --force --quiet "https://${3e4415b72d55127f03805604674e9c78a11f69c6}@${GH_REF}" master:master  #GITHUB_TOKEN为在TravisCI中添加的来自Github的授权Token，见上一步
  - hexo deploy

branches:
  only:
    - hexo

# 创建全局变量，与GithubPage仓库ssh地址一致
env:
 global:
   - GH_REF: git@github.com:FuJunZhi/FuJunZhi.github.io.git
